import random
from typing import Dict

word_bank = {
    "Fruit": [
        "mango",
        "banana",
        "apple",
        "orange",
        "watermelon",
        "dragonfruit",
        "cantalope",
        "kiwi",
        "pineapple",
    ],
    "Vegetable": [
        "lettuce",
        "onion",
        "celery",
        "tomato",
        "carrot",
        "potato",
        "cale",
        "pepper",
        "squash",
        "cucumber",
        "pickle",
    ],
    "Animal": [
        "dog",
        "monkey",
        "snake",
        "cat",
        "pig",
        "cow",
        "horse",
        "antelope",
        "hippopotamus",
        "lion",
        "tiger",
        "bear",
        "pigeon",
        "fish",
        "shark",
        "panda",
        "gorilla",
        "baboon",
        "penguin",
        "deer",
        "eagle",
        "falcon",
        "bat",
    ],
    "Sport": [
        "football",
        "soccer",
        "baseball",
        "basketball",
        "tennis",
        "hockey",
        "golf",
        "rugby",
        "iceskating",
        "boxing",
        "track",
    ],
    "Car": [
        "toyota",
        "ford",
        "hyundai",
        "tesla",
        "mercedez",
        "audi",
        "lamborghini",
        "ferrari",
        "batmobile",
    ],
    "Continent": ["africa", "europe", "america", "asia", "oceania", "antarctica"],
    "Instrument": [
        "guitar",
        "drum",
        "trumpet",
        "trombone",
        "clarinet",
        "banjo",
        "piano",
        "xylophone",
        "organ",
        "tuba",
        "bongo",
        "bassoon",
        "saxophone",
        "violin",
        "harp",
        "keyboard",
    ],
    "Organ": ["heart", "brain", "lungs", "pancreas", "liver", "stomach"],
    "Wizard 101 (elements)": [
        "fire",
        "death",
        "ice",
        "earth",
        "light",
        "water",
        "lightning",
    ],
    "Playing Cards (Suits, numbers, and faces)": [
        "ace",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "jack",
        "queen",
        "king",
        "joker",
        "heart",
        "club",
        "spade",
        "diamond",
    ],
    "Month": [
        "january",
        "february",
        "march",
        "april",
        "may",
        "june",
        "july",
        "august",
        "september",
        "october",
        "november",
        "december",
    ],
    "Hand Tool": [
        "hammer",
        "shovel",
        "saw",
        "chainsaw",
        "axe",
        "pickaxe",
        "mallet",
        "pliers",
        "crowbar",
    ],
    "Planet": [
        "mercury",
        "venus",
        "earth",
        "mars",
        "jupiter",
        "saturn",
        "uranus",
        "neptune",
    ],
    "Music Genre": [
        "rock",
        "country",
        "rap",
        "gospel",
        "pop",
        "metal",
        "classical",
        "jazz",
    ],
}


def randomCat():
    x = word_bank.keys()
    return random.choice(list(x))


def randomWord(cat):
    return random.choice(word_bank.get(cat))
